### ISSUE TITLE
Using `toString` on Uint8Array..

### ISSUE THREAD

**Issue by baruchvlz** [cgjs/cgjs#25]
Using `cgjs` library, terminal displays this warning coming from `cgjs/require.js:66`

```
 Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
```

**Comment by WebReflection** [comment]
if you are using this to have CommonJS only, please consider switching to https://github.com/WebReflection/gjs-require

otherwise, without any code, I've no idea how to reproduce this issue, but I am also on vacation without my Linux laptop, so I am not sure how to fix this, but I've just seen alerts about security issues with this project, so I'm back to suggesting https://github.com/WebReflection/gjs-require

**Comment by baruchvlz** [comment]
@WebReflection Well, the warning pop-up even in a dry run. But it's ok, I'm already using `gjs-require` :)

Happy holidays.
