### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by benwaffle** [cgjs/cgjs#4]
When running `cgjs` it should open a gjs prompt in the cgjs environment

**Comment by WebReflection** [comment]
until the repl module is in place, I'm not sure that's possible because GJS does not allow me to go in repl mode when you pass arguments.

I'm bootstrapping gjs (or cjs, if available) via bash configuring the infamous `GJS_DISABLE_EXTRA_WARNINGS` since GJS by default warns on simple missing properties per object, which is utterly annoying when you deal with third parts module (in this case the buffer)

if you know a way to put gjs in repl mode within the code, please let me know, thanks.

**Comment by ptomato** [comment]
This works, though I don't know if it's as customizable as you want:
```js
const Console = imports.console;
print('Welcome to my custom REPL!');
Console.interact();
```

**Comment by WebReflection** [comment]
thanks @ptomato it works on 0.1.16, use `--help` to see options, just type `cgjs` to enter interactively
