### ISSUE TITLE
Critical Syntax Error

### ISSUE THREAD

**Issue by cmonagle** [cgjs/cgjs#7]
When executing any `cgjs` command, I receive the following error:
```
(gjs:24298): Gjs-CRITICAL **: JS ERROR: SyntaxError: syntax error @ /usr/local/lib/node_modules/cgjs/cgjs/timers.js:36
JS_EvaluateScript() failed
```
Line 36 of timers.js is the first line inside the following function:
```
  this.setImmediate = (fn, ...args) => {
    const id = cgjsloop.idle(fn, ...args);
    ids.add(id);
    return id;
  };
```
I can't spot any obvious syntax errors.

GJS version:
- gjs:amd64/xenial 1.44.0-1ubuntu1 uptodate 
- libgjs0e:amd64/xenial 1.44.0-1ubuntu1 uptodate

Node versions:
- v6.10.3
- v8.7.0

Let me know if there's any other information you might need.

**Comment by WebReflection** [comment]
the node version is irrelevant, no NodeJS is involved here (which is the whole point) but it looks like you are in jurassic Linux.

You need at least js52 and gjs 50 or you can consider [jsgtk](https://github.com/WebReflection/jsgtk) instead.

Or you can upgrade to ubuntu 17 which should have modern stack.

**Comment by WebReflection** [comment]
P.S. this should probably be specified somewhere in the README, I will do that ASAP

**Comment by ewnd9** [comment]
> jurassic Linux

Xenial is a codename for Ubuntu 16.04 LTS, it's not that old

I've had moderate success with backports https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/gnome-3-26 

`$ gjs --version` shows `1.50.0` (and `cgjs` is running), but I had to rebuild gtk theme because of some incompatibilities, so proceed with caution

**Comment by WebReflection** [comment]
> Xenial is a codename for Ubuntu 16.04 LTS, it's not that old

it uses jurassic software then.

js52 landed in Linux quite some time ago and previous versions are not more stable, are rather just less capable.

It's your choice to be in LTS but I can tell you I have zero issues in ArchLinux for the last few years.

Same goes for Fedora users, probably for Ubuntu 17.x too.

Jut saying this because I won't suggest in this repository to rebuild gtk theme and I am not planning to support hybrid solutions (I have honestly no time for that).

Thanks fr your understanding, I'll still write the requirements, or make these more clear, in the main page.

**Comment by ewnd9** [comment]
> Jut saying this because I won't suggest in this repository to rebuild gtk theme and I am not planning to support hybrid solutions (I have honestly no time for that).

Sorry, it wasn't my intention to imply you have to, just sharing information for posterity. If anyone come up with idea to use backports for cgjs they could find my warning in this issue.

Also, to explain better my theme problem: if you use backports and update some of the packages, you might have to rebuild packages which depend on older versions of updated ones.
